// <auto-generated />
namespace baitapltw.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createTablePRODUCT_CATEGORY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTablePRODUCT_CATEGORY));
        
        string IMigrationMetadata.Id
        {
            get { return "202303201203225_createTable-PRODUCT_CATEGORY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
